### ISSUE TITLE
npm run dev error?

### ISSUE THREAD

**Issue by meua** [muxiaobai/graduation-project#2]
> node build/dev-server.js
child_process.js:526
    throw err;
    ^
    Error: Command failed: npm --version
    at checkExecSyncError (child_process.js:483:13)
    at Object.execSync (child_process.js:523:13)
    at exec (G:\graduation\graduation-project\vue\build\check-versions.js:6:35)
    at Object.<anonymous> (G:\graduation\graduation-project\vue\build\check-versions.js:17:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
s" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     G:\graduation\graduation-project\vue\npm-debug.log

**Comment by muxiaobai** [comment]
``` Error: Command failed: npm --version``` ,what is it ?
